import fs from 'node:fs';
import assert from 'node:assert/strict';

const read=rel=>fs.readFileSync(new URL(`../${rel}`,import.meta.url),'utf8');
const pkg=JSON.parse(read('package.json'));
const index=read('ui/index.html');
const runtime=read('ui/runtime-stability.js');
const screenshotJs=read('ui/zoom-screenshot-reference-2.0.41.js');
const screenshotCss=read('ui/zoom-screenshot-reference-2.0.41.css');
const physical=read('ui/zoom-physical-acceptance.js');
const profile=read('ui/profile-photo-fallback.js');
const personal=read('ui/personal-room.js');
const app=read('ui/app.js');
const activeShare=read('ui/active-share-home-parity-2.0.41.js');
const meetingParity=read('ui/meeting-parity.js');
const meetingNotifications=read('ui/meeting-notifications.js');
const shareService=read('src/share-service.mjs');
const shareRuntime=read('ui/share-runtime-authority-2.0.41.js');
const participantControls=read('ui/participant-controls.js');

assert.equal(pkg.version,'2.0.44','Executive Zoom parity repair must ship under 2.0.44.');
assert(!index.includes('participants-center-lock-2.0.41.js')&&!index.includes('host-tools-separation-lock-2.0.41.js'),'Conflicting legacy panel/host locks must not load.');
assert(!activeShare.includes('participants-center-lock-2.0.41.js')&&!activeShare.includes('DominionParticipantsCenterLock2041')&&!activeShare.includes('loadParticipantsCenterLock'),'Active-share restoration must not reintroduce or call the retired Participants center-lock authority.');
assert(activeShare.includes('retireBackgroundReconcilers?.()')&&activeShare.includes('primeParticipantsReference()'),'Late-loaded Participants reference must be structurally primed once and immediately retired.');
assert(runtime.includes("overlay.dataset.dsRuntimeSide='center-floating'")&&runtime.includes("Math.round((bodyWidth-pw)/2)"),'Participants and Chat must share one stable centered floating authority.');
assert(runtime.includes("document.addEventListener('pointermove',moveFloatingSurface,true)")&&runtime.includes("document.addEventListener('pointerup',endFloatingSurfaceDrag,true)"),'Floating panel drag must continue through document-level pointer movement after the pointer leaves the title bar.');
assert(runtime.includes("window.addEventListener('mousedown',beginDelegatedFloatingMouse,true)")&&runtime.includes("window.addEventListener('pointerdown',beginDelegatedFloatingPointer,true)")&&runtime.includes("window.addEventListener('mousemove',moveFloatingSurfaceMouse,true)"),'Floating panel drag must use the window capture phase so retired legacy listeners cannot intercept movement.');
assert(runtime.includes('function dragAxisDelta(event,state,axis)')&&runtime.includes('state.originLeft+deltaX')&&runtime.includes('state.originTop+deltaY'),'Floating drag must resolve movement from the captured drag origin rather than mixing viewport coordinates with the panel containing block.');
assert(runtime.includes("panel.dataset.dsAdaptiveUserPositioned='1'")&&runtime.includes("panel.dataset.dsAdaptiveInitialized='1'"),'Runtime drag must publish the shared user-positioned geometry state so visual-reference reconcilers cannot snap the Participants window back.');
assert(meetingParity.includes("head.dataset.dsParticipantDragAuthority='runtime-stability'")&&!meetingParity.includes("head.addEventListener('pointermove'"),'Meeting parity must not retain a second Participants pointer-drag authority.');
assert(read('ui/zoom-participants-reference-2.0.41.js').includes('.ds-participants-mac .room-side-head>button{display:grid!important'),'Participants close control must remain visible on Mac.');
assert(runtime.includes("'DominionZoomParticipantsReference2041'")&&runtime.includes("window.DominionZoomParticipantsReference2041?.sync?.()"),'Legacy participant chrome may prime once but its geometry reconciler must be retired.');
assert(runtime.includes('function openRuntimeHostTools(anchor)')&&runtime.includes('function installRuntimeHostToolsAuthority()')&&runtime.includes('void openRuntimeHostTools(host)')&&!runtime.includes("DominionMeetingParity?.openSecurity?.(hostTools)"),'Host Tools must have one canonical direct runtime owner.');
assert(screenshotJs.includes("host.dataset.dsRefHostBound='runtime-single-owner'"),'Screenshot compatibility layer must not bind a second Host Tools listener.');
assert(screenshotCss.includes('#prejoinOverlay #prejoinAvatar[hidden]{display:none!important}'),'Hidden prejoin avatar must stay hidden over live video.');
assert(profile.includes('videoActuallyLive')&&profile.includes("getVideoTracks?.()"),'Prejoin avatar fallback must follow the actual live video track.');
assert(physical.includes("roleText='(Host, me)'")&&physical.includes('.ds-canonical-participant-role')&&!physical.includes("badge.className='ds-role-chip'"),'Participant role presentation must be one Zoom-style suffix, never a duplicate badge.');
assert(physical.includes("dataset.dsReactionIcon='executive-smile'")&&physical.includes('M18.25 3.5v4M16.25 5.5h4')&&!physical.includes('M18 15.7c1.9'),'React toolbar must use the canonical smile-and-spark glyph without the rejected malformed tail.');
assert(physical.includes("row.dataset.participantSelf==='1'||(localParticipantId&&String(row.dataset.participantId||'')===String(localParticipantId))"),'Self participant More control must honor the authoritative row self marker without waiting for async meeting-context hydration.');
assert(physical.includes("participantObserver.observe(roster,{childList:true})")&&!physical.includes("participantObserver.observe(roster,{childList:true,subtree:true})"),'Participant observer must watch roster membership only and must not retrigger itself on decorated descendants.');
assert(physical.includes("wrap.dataset.dsMediaSignature!==signature"),'Participant media decoration must be state-signature idempotent rather than rewriting DOM every sync.');
assert(physical.includes("const suffixes=[...copy.querySelectorAll('.ds-canonical-participant-role')]"),'Canonical participant role decoration must deduplicate in place without remove/recreate churn.');
assert(physical.includes(".ds-participant-self-label,.ds-canonical-participant-role"),'Canonical participant role decoration must remove its prior suffix before re-rendering.');
assert(screenshotJs.includes(".zoom-participant-footer,#meetingOverlay .room-side #participantBulkActions"),'Final Participants footer must remove legacy duplicate action bars.');
assert(screenshotJs.includes("footer.hidden=false;footer.removeAttribute('hidden');footer.removeAttribute('data-ds-legacy-participant-actions')"),'Canonical Participants footer must be explicitly revived after panel toggles instead of remaining hidden.');
assert(!participantControls.includes("footer.id='participantBulkActions'")&&participantControls.includes("q('#participantBulkActions')?.remove()"),'Participant controls must retire the legacy bulk-action footer instead of recreating a second owner.');
assert(screenshotJs.includes('data-stop-video')&&screenshotJs.includes('data-start-video')&&screenshotJs.includes('data-lower-hands'),'Canonical Participants More menu must retain meeting-wide video and hand controls after legacy footer retirement.');
assert(runtime.includes("host.onclick=event=>")&&runtime.includes("host.dataset.dsPhysicalAuthority='runtime-owned'")&&runtime.includes('installRuntimeHostToolsAuthority();'),'Host Tools must be rebound directly to the runtime owner after legacy priming.');
assert(!meetingNotifications.includes("target.closest('#roomHostTools')")&&!meetingNotifications.includes('openHostToolsPanel?.()'),'Window-capture notification routing must not intercept the canonical runtime-owned Host Tools button.');
assert(shareService.includes("shareAudio:Boolean(options.shareAudio)&&platform==='win32'")&&shareService.includes("if(selection.options?.shareAudio&&platform==='win32')response.audio='loopback'")&&!shareService.includes("platform==='win32'||platform==='darwin'"),'macOS screen sharing must not request Electron loopback audio, which is unsupported by setDisplayMediaRequestHandler on macOS.');
assert(shareRuntime.includes("if(input&&platform==='darwin')")&&shareRuntime.includes('input.checked=false;input.disabled=true'),'The macOS share chooser must not expose an enabled Share sound control while the supported capture path is video-only.');
assert(runtime.includes("data-ds-runtime-close-participants")||runtime.includes("dataset.dsRuntimeCloseParticipants='1'"),'Participants must expose a direct close control.');
assert(personal.includes("passInput.value=String(state.room.passcode||'')")&&personal.includes("passLabel.style.setProperty('display',personal?'none':'','important')"),'Personal Meeting ID mode must not expose a stale alternate passcode.');
assert(app.includes("if(!target){")&&app.includes("prejoinVideo.hidden=true"),'Camera-off feedback must remain immediate.');
assert(app.includes("installedInApplications===false&&!info?.qaInteractionRequested"),'Explicit QA interaction runs must not be covered by the intentional non-Applications install warning dialog.');
assert(read('src/main.mjs').includes('qaInteractionRequested:qaFixtureRequested'),'Renderer environment must expose the explicit QA interaction request independently of release-channel fixture enablement.');

console.log('DOMINIONSTAR_EXECUTIVE_ZOOM_PARITY_2_0_44_OK single-layout-authority centered-floating-panels single-host-tools prejoin-video-exclusive canonical-participant-role direct-close clean-personal-passcode');
