import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';

const appPath=process.argv[2];
const proofPath=process.argv[3]?path.resolve(process.argv[3]):'';
if(!appPath)throw new Error('Usage: node verify-packaged-mac-presenter-window-2.0.41.mjs <DominionStar Meet.app> [toolbar-proof.png]');
const executable=path.resolve(appPath,'Contents','MacOS','DominionStar Meet');
const port=12140+Math.floor(Math.random()*120);
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let stderr='';
const child=spawn(executable,[`--remote-debugging-port=${port}`,'--remote-allow-origins=*'],{env:{...process.env,ELECTRON_ENABLE_LOGGING:'1',DOMINIONSTAR_QA_INTERACTION_FIXTURES:'1',DOMINIONSTAR_QA_KEEP_MAC_PRESENTER_HIDDEN:'1'},stdio:['ignore','ignore','pipe']});
child.stderr.on('data',chunk=>{stderr+=String(chunk);});
const count=needle=>stderr.split(String(needle)).length-1;
async function waitLog(needle,label,timeout=9000,minCount=1){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(child.exitCode!==null)throw new Error(`App exited before ${label}.\n${stderr}`);if(stderr.includes('QA_MAC_HOSTED_FAILURE'))throw new Error(`Hosted presenter fixture failed before ${label}.\n${stderr}`);if(count(needle)>=minCount)return;await sleep(60);}throw new Error(`Timed out waiting for ${label}: ${needle}\n${stderr}`);}
async function target(predicate,label,timeout=15000){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(child.exitCode!==null)throw new Error(`App exited before ${label}.\n${stderr}`);try{const response=await fetch(`http://127.0.0.1:${port}/json/list`,{signal:AbortSignal.timeout(800)});if(response.ok){const targets=await response.json();const found=targets.find(item=>item.type==='page'&&predicate(String(item.url||''))&&item.webSocketDebuggerUrl);if(found)return found;}}catch{}await sleep(100);}throw new Error(`Timed out waiting for ${label}.\n${stderr}`);}
class Cdp{constructor(url){this.url=url;this.socket=null;this.next=0;this.pending=new Map();}async connect(){this.socket=await new Promise((resolve,reject)=>{const socket=new WebSocket(this.url),timer=setTimeout(()=>reject(new Error('CDP connect timeout')),4000);socket.addEventListener('open',()=>{clearTimeout(timer);resolve(socket);},{once:true});socket.addEventListener('error',()=>{clearTimeout(timer);reject(new Error('CDP connect failed'));},{once:true});});this.socket.addEventListener('message',event=>{const msg=JSON.parse(String(event.data));if(!msg.id)return;const waiter=this.pending.get(msg.id);if(!waiter)return;this.pending.delete(msg.id);clearTimeout(waiter.timer);msg.error?waiter.reject(new Error(msg.error.message||'CDP error')):waiter.resolve(msg.result);});await this.call('Runtime.enable');await this.call('Page.enable');}call(method,params={},timeout=7000){return new Promise((resolve,reject)=>{const id=++this.next,timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(`CDP timeout ${method}`));},timeout);this.pending.set(id,{resolve,reject,timer});this.socket.send(JSON.stringify({id,method,params}));});}async eval(expression,timeout=7000){const result=await this.call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},timeout);if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text||'Renderer evaluation failed');return result.result?.value;}async wait(expression,label,timeout=10000){const deadline=Date.now()+timeout;while(Date.now()<deadline){try{if(await this.eval(`Boolean(${expression})`,2500))return;}catch{}await sleep(80);}throw new Error(`Timed out waiting for ${label}.`);}async screenshot(file){const result=await this.call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false,fromSurface:true});fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,Buffer.from(result.data,'base64'));}close(){try{this.socket?.close();}catch{}}}

let main=null,toolbar=null,video=null,failure=null;
try{
  const mainTarget=await target(url=>url.startsWith('file://')&&url.includes('/ui/index.html'),'meeting renderer');main=new Cdp(mainTarget.webSocketDebuggerUrl);await main.connect();
  await main.wait("document.readyState==='complete'&&window.DominionShareController&&window.DominionShareIntegration&&window.__DominionPresenterDispatch&&window.dominionDesktop?.macShare?.prepare",'share/presenter controllers');
  const prepared=await main.eval(`window.dominionDesktop.macShare.prepare()`,12000);assert.equal(prepared?.ok,true,'Native macOS presenter surfaces did not prepare.');
  toolbar=new Cdp((await target(url=>url.includes('mac-presenter-toolbar.html'),'floating presenter toolbar')).webSocketDebuggerUrl);await toolbar.connect();await toolbar.wait("document.readyState==='complete'&&document.querySelector('#stopShare')&&window.DominionMacPresenterToolbar?.transport==='macShare-ack'",'acknowledged native presenter bridge');
  video=new Cdp((await target(url=>url.includes('mac-share-video.html'),'floating participant video dock')).webSocketDebuggerUrl);await video.connect();await video.wait("document.readyState==='complete'&&document.querySelector('#dock')",'floating participant video dock');
  const surface=await toolbar.eval(`(()=>({brand:document.querySelector('.brand span')?.textContent||'',stop:document.querySelector('#stopShare')?.textContent||'',transport:window.DominionMacPresenterToolbar?.transport||'',commands:[...document.querySelectorAll('[data-command]')].map(n=>n.dataset.command)}))()`);assert.equal(surface.brand,'DominionStar');assert.match(surface.stop,/Stop share/i);assert.equal(surface.transport,'macShare-ack');for(const command of ['participants','chat','pause','annotate','show-meeting'])assert.ok(surface.commands.includes(command),`Missing ${command} on native toolbar.`);if(proofPath)await toolbar.screenshot(proofPath);
  const armed=await main.eval(`(()=>{
    document.querySelector('#bootScreen').hidden=true;document.querySelector('#authGate').hidden=true;document.querySelector('#appShell').hidden=true;document.querySelector('#prejoinOverlay').hidden=true;document.querySelector('#waitingOverlay').hidden=true;const overlay=document.querySelector('#meetingOverlay');overlay.hidden=false;const role=document.querySelector('#roomRole');if(role)role.textContent='Host';window.DominionMeetingParity?.install?.();window.DominionMeetingFeatures?.toggleChat?.(false);window.DominionRuntimeStability?.sync?.();
    window.__qaHostedPrev={active:false,paused:false};window.DominionShareController.onChange(state=>{const prev=window.__qaHostedPrev||{active:false,paused:false};console.error('QA_MAC_HOSTED_STATE active='+(state.active?1:0)+' paused='+(state.paused?1:0));if(state.active&&state.paused&&!prev.paused)console.error('QA_MAC_HOSTED_PAUSED');if(state.active&&!state.paused&&prev.paused)console.error('QA_MAC_HOSTED_RESUMED');if(!state.active&&prev.active)console.error('QA_MAC_HOSTED_STOPPED');window.__qaHostedPrev={active:Boolean(state.active),paused:Boolean(state.paused)};});window.addEventListener('dominion:presenter-command-dispatch',event=>console.error('QA_MAC_HOSTED_COMMAND '+String(event.detail?.command||'')));window.__qaHostedCompanion='';new MutationObserver(()=>{const kind=String(document.body.dataset.dsShareCompanion||'none');if(kind!==window.__qaHostedCompanion){window.__qaHostedCompanion=kind;console.error('QA_MAC_HOSTED_COMPANION '+kind);}}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['data-ds-share-companion','hidden']});
    const makeTrack=(kind='video')=>({kind,id:'qa-hosted-'+kind+'-'+Math.random().toString(36).slice(2),label:'QA Hosted '+kind,readyState:'live',enabled:true,contentHint:'',addEventListener(){},removeEventListener(){},stop(){this.readyState='ended';},clone(){return makeTrack(kind);}});const makeStream=(kind='video')=>{const tracks=[makeTrack(kind)];return {getVideoTracks:()=>tracks.filter(t=>t.kind==='video'),getAudioTracks:()=>tracks.filter(t=>t.kind==='audio'),getTracks:()=>[...tracks],addTrack(track){if(track&&!tracks.includes(track))tracks.push(track);},removeTrack(track){const i=tracks.indexOf(track);if(i>=0)tracks.splice(i,1);}};};
    const nativeSrcObject=Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype,'srcObject');Object.defineProperty(HTMLMediaElement.prototype,'srcObject',{configurable:true,get(){return Object.prototype.hasOwnProperty.call(this,'__qaLogicalSrcObject')?this.__qaLogicalSrcObject:nativeSrcObject?.get?.call(this)||null;},set(value){if(value&&!(value instanceof MediaStream)){this.__qaLogicalSrcObject=value;return;}delete this.__qaLogicalSrcObject;if(nativeSrcObject?.set)nativeSrcObject.set.call(this,value);}});HTMLCanvasElement.prototype.captureStream=function(){return makeStream('video');};const frameCanvas=document.createElement('canvas');frameCanvas.width=640;frameCanvas.height=360;const ctx=frameCanvas.getContext('2d',{alpha:false});ctx.fillStyle='#07111f';ctx.fillRect(0,0,640,360);ctx.fillStyle='#d6b25e';ctx.fillRect(70,70,210,130);Object.defineProperty(window,'ImageCapture',{configurable:true,value:class{async grabFrame(){return createImageBitmap(frameCanvas);}}});Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{configurable:true,value:async()=>makeStream('video')});
    setTimeout(async()=>{try{const state=await window.DominionShareController.start({name:'QA Mac Floating Share',options:{shareAudio:false,optimizeVideo:false}});console.error('QA_MAC_HOSTED_SHARE active='+(state.active?1:0));setTimeout(()=>console.error('QA_MAC_HOSTED_TICK'),120);}catch(error){console.error('QA_MAC_HOSTED_FAILURE '+String(error?.stack||error));}},120);return true;
  })()`,4000);assert.equal(armed,true,'Hosted native presenter fixture was not armed.');
  main.close();main=null;
  await waitLog('QA_MAC_CAPTURE_STARTED_ACK_ONLY','logical-share capture acknowledgement isolation');await waitLog('QA_MAC_HOSTED_SHARE active=1','logical active share');await waitLog('QA_MAC_HOSTED_TICK','responsive hosted renderer');
  await toolbar.eval(`document.querySelector('[data-command="pause"]').click()`);await waitLog('QA_MAC_HOSTED_COMMAND pause','Pause native delivery',5000,1);await waitLog('QA_MAC_HOSTED_PAUSED','Pause round trip');await waitLog('QA_MAC_PRESENTER_ACK','Pause native acknowledgement');
  await toolbar.eval(`document.querySelector('[data-command="pause"]').click()`);await waitLog('QA_MAC_HOSTED_COMMAND pause','Resume native delivery',5000,2);await waitLog('QA_MAC_HOSTED_RESUMED','Resume round trip');await waitLog('QA_MAC_PRESENTER_ACK','Resume native acknowledgement',5000,2);
  await toolbar.eval(`document.querySelector('[data-command="participants"]').click()`);await waitLog('QA_MAC_HOSTED_COMMAND participants','Participants native delivery');await waitLog('QA_MAC_HOSTED_COMPANION participants','Participants companion');
  await toolbar.eval(`document.querySelector('[data-command="chat"]').click()`);await waitLog('QA_MAC_HOSTED_COMMAND chat','Chat native delivery');await waitLog('QA_MAC_HOSTED_COMPANION chat','Chat companion');
  await toolbar.eval(`document.querySelector('#stopShare').click()`);await waitLog('QA_MAC_HOSTED_COMMAND stop','Stop Share native delivery');await waitLog('QA_MAC_HOSTED_STOPPED','Stop Share round trip');
  console.log('DOMINIONSTAR_PACKAGED_MAC_PRESENTER_WINDOW_2_0_41_OK native-toolbar native-video-dock macShare-ack prepared-hidden-surfaces logical-share-controller pause-resume participants-chat stop-share physical-visible-tcc-required');
}catch(error){failure=error;console.error(error?.stack||String(error));if(stderr.trim())console.error(stderr.trim());}
finally{video?.close();toolbar?.close();main?.close();if(child.exitCode===null){try{child.kill('SIGTERM');}catch{}await sleep(300);if(child.exitCode===null)try{child.kill('SIGKILL');}catch{}}}
if(failure)throw failure;
