(()=>{
  if(window.DominionPreferences)return;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],media=()=>window.DominionMediaController||null,desktop=window.dominionDesktop||{};
  const KEYS=Object.freeze({joinMuted:'ds_pref_join_muted',joinVideoOff:'ds_pref_join_video_off',showJoinPreview:'ds_pref_show_join_preview',hideSelfView:'ds_pref_hide_self_view',shareVideoDock:'ds_pref_share_video_dock',shareOptimize:'ds_pref_share_optimize',shareAudio:'ds_pref_share_audio',chatSound:'ds_pref_chat_sound',recordMic:'ds_pref_record_mic',recordRemote:'ds_pref_record_remote',uiScale:'ds_pref_ui_scale',shortcuts:'ds_pref_shortcuts'});
  const defaults={joinMuted:true,joinVideoOff:false,showJoinPreview:true,hideSelfView:false,shareVideoDock:true,shareOptimize:false,shareAudio:false,chatSound:true,recordMic:true,recordRemote:true,uiScale:'100',shortcuts:true};
  const read=(name)=>{try{const raw=localStorage.getItem(KEYS[name]);if(raw===null)return defaults[name];if(typeof defaults[name]==='boolean')return raw==='1';return raw;}catch{return defaults[name];}};
  const write=(name,value)=>{try{localStorage.setItem(KEYS[name],typeof defaults[name]==='boolean'?(value?'1':'0'):String(value));}catch{}applyGlobal();};
  const snapshot=()=>Object.fromEntries(Object.keys(defaults).map(key=>[key,read(key)]));
  let installed=false,prejoinApplied=false;

  function applyGlobal(){const scale=Math.max(90,Math.min(125,Number(read('uiScale'))||100));document.documentElement.style.setProperty('--ds-ui-scale',String(scale/100));document.body.style.zoom=String(scale/100);document.body.classList.toggle('ds-hide-self-view',Boolean(read('hideSelfView')));window.dispatchEvent(new CustomEvent('dominion:preference-change',{detail:snapshot()}));}
  function detail(){const dialog=q('#settingsDialog');if(!dialog)return null;let node=q('#avSettingsDetail');if(!node){node=document.createElement('section');node.id='avSettingsDetail';node.className='av-settings-detail';dialog.querySelector('form')?.insertBefore(node,dialog.querySelector('.settings-note'));}dialog.querySelector('.settings-list').hidden=true;dialog.querySelector('.settings-note').hidden=true;node.hidden=false;return node;}
  function showList(){const dialog=q('#settingsDialog');if(!dialog)return;dialog.querySelector('.settings-list').hidden=false;dialog.querySelector('.settings-note').hidden=false;const node=q('#avSettingsDetail');if(node)node.hidden=true;}
  function heading(node,title,copy){node.innerHTML='';const head=document.createElement('header');head.className='av-detail-head';head.innerHTML=`<button type="button" class="secondary-button av-back">‹ Back</button><div><h3>${title}</h3><p>${copy}</p></div>`;head.querySelector('button').onclick=showList;node.append(head);}
  function toggle(node,label,name,copy=''){const row=document.createElement('label');row.className='av-toggle-row';const text=document.createElement('span');text.innerHTML=`${label}${copy?`<small style="display:block;margin-top:3px;color:#7f91a4;font-weight:500">${copy}</small>`:''}`;const input=document.createElement('input');input.type='checkbox';input.checked=Boolean(read(name));input.onchange=()=>write(name,input.checked);row.append(text,input);node.append(row);return input;}
  function select(node,label,name,options){const field=document.createElement('label');field.className='av-field';const span=document.createElement('span');span.textContent=label;const select=document.createElement('select');for(const [value,text] of options){const option=document.createElement('option');option.value=value;option.textContent=text;select.append(option);}select.value=String(read(name));select.onchange=()=>write(name,select.value);field.append(span,select);node.append(field);return select;}
  function info(node,text){const card=document.createElement('div');card.className='av-info-card';card.textContent=text;node.append(card);}

  function openMeetings(){const node=detail();if(!node)return;heading(node,'Meetings','Defaults applied when starting or joining a meeting.');toggle(node,'Always join with microphone muted','joinMuted','You can still unmute before joining.');toggle(node,'Always join with camera off','joinVideoOff','You can still start video before joining.');toggle(node,'Show video preview before joining','showJoinPreview','Turn this off to enter using your saved microphone and camera defaults.');toggle(node,'Hide my self view in meetings','hideSelfView','Your camera stays on for other participants; only your local self view is hidden.');info(node,'Waiting Room, host/co-host authority, participant admission, Leave, and End Meeting remain controlled by each meeting rather than by a global preference.');}
  function openSharing(){const node=detail();if(!node)return;heading(node,'Share Screen','Defaults for the DominionStar Screens / Applications chooser and participant video panel.');toggle(node,'Show participant video while sharing','shareVideoDock','The adaptive participant video panel floats over shared content.');toggle(node,'Optimize for video sharing by default','shareOptimize');toggle(node,'Share system audio by default','shareAudio','Used when the operating system and selected source support system-audio capture.');}
  function openChat(){const node=detail();if(!node)return;heading(node,'Chat','Meeting-chat behavior.');toggle(node,'Play a notification sound for new messages','chatSound');info(node,'Chat is available only to admitted meeting participants. Messages are transported through the authenticated meeting signaling layer.');}
  function openRecording(){const node=detail();if(!node)return;heading(node,'Recording','Local recording choices for this desktop.');toggle(node,'Include my microphone','recordMic');toggle(node,'Include participant audio','recordRemote');info(node,'Record captures the active meeting/share stage and downloads a local WebM recording when you stop. No cloud recording is created by this QA build.');}
  function openAccessibility(){const node=detail();if(!node)return;heading(node,'Accessibility','Adjust the desktop interface without changing meeting media.');select(node,'Interface size','uiScale',[['90','90%'],['100','100%'],['110','110%'],['125','125%']]);info(node,'The setting applies immediately and is remembered on this desktop.');}
  function openShortcuts(){const node=detail();if(!node)return;heading(node,'Keyboard Shortcuts','Familiar meeting shortcuts while DominionStar Meet is focused.');toggle(node,'Enable meeting keyboard shortcuts','shortcuts');info(node,'Option+A: mute/unmute · Option+V: start/stop video · Option+S: share screen · Option+H: open/close chat.');}
  async function openAbout(){const node=detail();if(!node)return;heading(node,'About','DominionStar Meet desktop information.');let env={};try{env=await desktop.environment?.()||{};}catch{}info(node,`DominionStar Meet ${String(env.version||'2.0.0 QA')} · ${String(env.platform||navigator.platform)}. Clean desktop rebuild with local Home, PKCE authentication, Meet V2 lifecycle, WebRTC media, and isolated screen sharing.`);}

  function addRow(list,title,copy,handler){let row=qa('.settings-row').find(item=>item.querySelector('strong')?.textContent?.trim()===title);if(!row){row=document.createElement('button');row.type='button';row.className='settings-row';row.innerHTML=`<span><strong>${title}</strong><small>${copy}</small></span><span>›</span>`;list.append(row);}row.onclick=handler;return row;}
  function installSettings(){const dialog=q('#settingsDialog'),list=dialog?.querySelector('.settings-list');if(!dialog||!list)return false;addRow(list,'Meetings','Join defaults and meeting behavior',openMeetings);addRow(list,'Sharing','Screen-share defaults',openSharing);addRow(list,'Chat','Message notifications',openChat);addRow(list,'Recording','Local recording preferences',openRecording);addRow(list,'Accessibility','Interface size and readability',openAccessibility);addRow(list,'Keyboard Shortcuts','Meeting keyboard controls',openShortcuts);addRow(list,'About','Version and desktop information',()=>void openAbout());dialog.addEventListener('close',showList);installed=true;return true;}

  async function applyPrejoinDefaults(){const overlay=q('#prejoinOverlay');if(!overlay||overlay.hidden){prejoinApplied=false;return;}if(prejoinApplied)return;prejoinApplied=true;const controller=media();if(!controller)return;try{if(read('joinMuted'))await controller.setMicrophone(false);if(read('joinVideoOff'))await controller.setCamera(false);}catch{};
    await showPrejoinCredentials();
  }
  async function showPrejoinCredentials(){const overlay=q('#prejoinOverlay'),windowNode=overlay?.querySelector('.prejoin-window');if(!windowNode||overlay.hidden)return;let ctx={};try{ctx=await desktop.meeting?.context?.()||{};}catch{}const roomCode=String(ctx.roomCode||'').replace(/\D/g,'').replace(/(\d{3})(?=\d)/g,'$1 ').trim(),pass=String(ctx.passcode||'');let box=q('#prejoinMeetingCredentials');if(!roomCode){box?.remove();return;}if(!box){box=document.createElement('div');box.id='prejoinMeetingCredentials';box.className='av-info-card prejoin-meeting-credentials';windowNode.querySelector('.preview-frame')?.insertAdjacentElement('beforebegin',box);}box.innerHTML=`<div><span>Meeting ID</span><strong>${roomCode}</strong><button type="button" data-copy-id>Copy</button></div><div><span>Passcode</span><strong>${pass}</strong><button type="button" data-copy-pass>Copy</button></div>`;box.querySelector('[data-copy-id]').onclick=()=>navigator.clipboard?.writeText?.(String(ctx.roomCode||''));box.querySelector('[data-copy-pass]').onclick=()=>navigator.clipboard?.writeText?.(pass);}

  function applyShareDockPreference(){const active=window.DominionShareController?.snapshot?.().active,dock=q('#participantVideoDock');if(!active||!dock)return;if(!read('shareVideoDock'))dock.hidden=true;else window.DominionMeetingParity?.syncVideoDock?.();}
  function handleShortcut(event){if(!read('shortcuts')||!event.altKey||event.metaKey||event.ctrlKey||event.shiftKey||event.target?.matches?.('input,textarea,select,[contenteditable="true"]'))return;const key=event.key.toLowerCase();const map={a:'#roomMic',v:'#roomCamera',s:'#roomShare',h:'#roomChat'},selector=map[key];if(!selector)return;const button=q(selector);if(!button||button.disabled||button.offsetParent===null)return;event.preventDefault();button.click();}

  window.addEventListener('keydown',handleShortcut,true);
  const observer=new MutationObserver(()=>{if(!installed)installSettings();void applyPrejoinDefaults();applyShareDockPreference();});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','class']});
  setInterval(()=>{if(!installed)installSettings();void applyPrejoinDefaults();applyShareDockPreference();},700);
  applyGlobal();installSettings();
  window.DominionPreferences=Object.freeze({read,write,snapshot,openMeetings,openSharing,openChat,openRecording,openAccessibility,openShortcuts,openAbout,applyPrejoinDefaults,applyShareDockPreference});
})();
